from app.models.user import User
from app.models.academic_section import AcademicSection
from app.models.student import Student
from app.models.teacher import Teacher
from app.models.subject import Subject
from app.models.teacher_assignment import TeacherAssignment
from app.models.attendance import Attendance
from app.models.assessment import Assessment
from app.models.result import Result